/* Generated by spimdisasm 1.35.0 */

.align 3
glabel func_00100000
    /* 1000 00100000 00000000 */  nop
.size func_00100000, . - func_00100000
    /* 1004 00100004 00000000 */  nop

.align 3
glabel func_00100008
    /* 1008 00100008 280C0070 */  padduw     $at, $zero, $zero
    /* 100C 0010000C 28140070 */  padduw     $v0, $zero, $zero
    /* 1010 00100010 281C0070 */  padduw     $v1, $zero, $zero
    /* 1014 00100014 28240070 */  padduw     $a0, $zero, $zero
    /* 1018 00100018 282C0070 */  padduw     $a1, $zero, $zero
    /* 101C 0010001C 28340070 */  padduw     $a2, $zero, $zero
    /* 1020 00100020 283C0070 */  padduw     $a3, $zero, $zero
    /* 1024 00100024 28440070 */  padduw     $t0, $zero, $zero
    /* 1028 00100028 284C0070 */  padduw     $t1, $zero, $zero
    /* 102C 0010002C 28540070 */  padduw     $t2, $zero, $zero
    /* 1030 00100030 285C0070 */  padduw     $t3, $zero, $zero
    /* 1034 00100034 28640070 */  padduw     $t4, $zero, $zero
    /* 1038 00100038 286C0070 */  padduw     $t5, $zero, $zero
    /* 103C 0010003C 28740070 */  padduw     $t6, $zero, $zero
    /* 1040 00100040 287C0070 */  padduw     $t7, $zero, $zero
    /* 1044 00100044 28840070 */  padduw     $s0, $zero, $zero
    /* 1048 00100048 288C0070 */  padduw     $s1, $zero, $zero
    /* 104C 0010004C 28940070 */  padduw     $s2, $zero, $zero
    /* 1050 00100050 289C0070 */  padduw     $s3, $zero, $zero
    /* 1054 00100054 28A40070 */  padduw     $s4, $zero, $zero
    /* 1058 00100058 28AC0070 */  padduw     $s5, $zero, $zero
    /* 105C 0010005C 28B40070 */  padduw     $s6, $zero, $zero
    /* 1060 00100060 28BC0070 */  padduw     $s7, $zero, $zero
    /* 1064 00100064 28C40070 */  padduw     $t8, $zero, $zero
    /* 1068 00100068 28CC0070 */  padduw     $t9, $zero, $zero
    /* 106C 0010006C 28E40070 */  padduw     $gp, $zero, $zero
    /* 1070 00100070 28EC0070 */  padduw     $sp, $zero, $zero
    /* 1074 00100074 28F40070 */  padduw     $fp, $zero, $zero
    /* 1078 00100078 28FC0070 */  padduw     $ra, $zero, $zero
    /* 107C 0010007C 11000000 */  mthi       $zero
    /* 1080 00100080 11000070 */  mthi1      $zero
    /* 1084 00100084 13000000 */  mtlo       $zero
    /* 1088 00100088 13000070 */  mtlo1      $zero
    /* 108C 0010008C 00001904 */  mtsah      $zero, 0x0
    /* 1090 00100090 00008044 */  mtc1       $zero, $f0
    /* 1094 00100094 00088044 */  mtc1       $zero, $f1
    /* 1098 00100098 00108044 */  mtc1       $zero, $f2
    /* 109C 0010009C 00188044 */  mtc1       $zero, $f3
    /* 10A0 001000A0 00208044 */  mtc1       $zero, $f4
    /* 10A4 001000A4 00288044 */  mtc1       $zero, $f5
    /* 10A8 001000A8 00308044 */  mtc1       $zero, $f6
    /* 10AC 001000AC 00388044 */  mtc1       $zero, $f7
    /* 10B0 001000B0 00408044 */  mtc1       $zero, $f8
    /* 10B4 001000B4 00488044 */  mtc1       $zero, $f9
.size func_00100008, . - func_00100008
