name: SSX 3 (2003) (USA)
sha1: 77114dfd1205eaccf1ccc18c5f9650097fa78bd8

options:
  basename: SLUS_207.72
  target_path: disc/SLUS_207.72
  elf_path: SLUS_207.72
  base_path: ../
  platform: ps2
  compiler: EEGCC

  asm_path: asm
  src_path: src/
  build_path: obj

  # Put 'hasm' splits in src/
  hasm_in_src_path: True

  rodata_string_guesser_level: 0

  find_file_boundaries: False
  disasm_unknown: True
  named_regs_for_c_funcs: False

  create_undefined_funcs_auto: True
  undefined_funcs_auto_path: config/undefined_funcs_auto.txt
  create_undefined_syms_auto: True
  undefined_syms_auto_path: config/undefined_syms_auto.txt

  symbol_addrs_path: [ config/symbol_addrs.txt, config/lib_symbol_addrs.txt ]

  extensions_path: tools/splat_ext

  section_order: [".text", ".vutext", ".data", ".rodata", ".lit4", ".sbss", ".bss"]
  auto_link_sections: [".data", ".rodata", ".bss"]

  subalign: 4

segments:
  - name: elf_header
    type: databin
    start: 0x0
    
  - name: main
    type: code
    start: 0x1000
    vram: 0x100000
    bss_size: 0x099EDB # I think?
    subsegments:
      - [0x1000, asm, sce/crt0]
        
      - [0x1218, asm]
      
      - [0x1dc6d8, cpp, visualfx/crowdrender2d]
      
      - [0x1dcd10, asm]
      
      - [0x218618, cpp, hashvalue]
      
      - [0x2187c8, cpp, bxrandom]
      
      - [0x218ae8, asm]
      
      - [0x218fe8, cpp, bx/bxstring]
      
      - [0x21a1c0, asm]
      
      - [0x21d350, cpp, md5]
      
      - [0x21E5A8, asm]
      
      - [0x2ec198, cpp, dirtysock/tags]
      
      - [0x2eef50, asm]
      
      # --- .vutext
      - [0x32f590, textbin, vutext]

      # --- .data
      - [0x33de00, data]

      # --- .rodata
      - [0x357900, rodata]
      
      - [0x39c080, rodatabin, gcc_except_table]
      
      - [0x39c100, lit4]

  - [0x3B5E60]